apiVersion: apps/v1
kind: Deployment
metadata:
  name: yapi
  labels:
    app: yapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yapi
  template:
    metadata:
      labels:
        app: yapi
    spec:
      containers:
        - name: yapi
          image: hachikozjq/yapi:0.0.5
          env:
            - name: YAPI_ADMINACCOUNT
              value: 343122875@qq.com
            - name: YAPI_DB_SERVERNAME
              value: 172.26.21.252
            - name: YAPI_DB_DATABASE
              value: yapi-back
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: yapi
spec:
  selector:
    app: yapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
